printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
# tslintIntegration: true
# arrowParens: avoid
## Disable, otherwise won't work with JSON files
# parser: "typescript"
